config/routes.rb
Myapp::Application.routes.draw do
  devise_for :appusers

  resources :expenses
  resources :users

  get "welcome/index"

  resources :posts  
 

  match "login", :to => "sessions#login"
  
  root :to => 'welcome#index'

end

app/models/appuser.rb
class Appuser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/expense.rb
class Expense < ActiveRecord::Base
  attr_accessible :amount, :categories, :description, :email
  validates :amount, :presence => true
  #validates :categories, inclusion: ['food','transportation','clothing']
  validates :description, :presence => true, :length => {:minimum => 2}
  EMAIL_REGEX = /^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}$/i
  validates :email, :presence => true, :format => EMAIL_REGEX

end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :text, :title
  validates :title, presence: true, length: { minimum: 5 }
  validates :title, :presence => true, :length => { :minimum => 2 }
end

app/models/user.rb
class User < ActiveRecord::Base
   attr_accessible :firstname, :lastname, :email, :password, :password_confirmation
    attr_accessor :password
	EMAIL_REGEX = /^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}$/i
	#validates :username, :presence => true, :uniqueness => true, :length => { :in => 3..20 }
	validates :email, :presence => true, :uniqueness => true, :format => EMAIL_REGEX
	validates :password, :confirmation => true #password_confirmation attr
	validates_length_of :password, :in => 6..20, :on => :create
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  # GET /expenses
  # GET /expenses.json
  def index
    @expenses = Expense.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @expenses }
    end
  end

  # GET /expenses/1
  # GET /expenses/1.json
  def show
    @expense = Expense.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @expense }
    end
  end

  # GET /expenses/new
  # GET /expenses/new.json
  def new
    @expense = Expense.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @expense }
    end
  end

  # GET /expenses/1/edit
  def edit
    @expense = Expense.find(params[:id])
  end

  # POST /expenses
  # POST /expenses.json
  def create
    @expense = Expense.new(params[:expense])

    respond_to do |format|
      if @expense.save
        format.html { redirect_to @expense, notice: 'Expense was successfully created.' }
        format.json { render json: @expense, status: :created, location: @expense }
      else
        format.html { render action: "new" }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /expenses/1
  # PUT /expenses/1.json
  def update
    @expense = Expense.find(params[:id])

    respond_to do |format|
      if @expense.update_attributes(params[:expense])
        format.html { redirect_to @expense, notice: 'Expense was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /expenses/1
  # DELETE /expenses/1.json
  def destroy
    @expense = Expense.find(params[:id])
    @expense.destroy

    respond_to do |format|
      format.html { redirect_to expenses_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	def new
		@post = Post.new
		
		respond_to do |format|
			format.html # new.html.erb
			format.json { render :json => @post}
		end
	end

	def create
	  @post = Post.new(params[:post]) 
	  #@post = Post.new(post_params)
	  #render text: params[:post].inspect
	  respond_to do |format|
		  if @post.save
		  	format.html { redirect_to(@post, :notice => 'post was successfully created')}
			format.json { render :json => @post, :status => :created, :location => @post }
		  else
		  	format.html {render :action => "new" }
		  	format.json {render :json => @post.errors, :status => :unprocessable_entity}
	  	   end
	  	end
	end

	def show
		@post = Post.find(params[:id])


	  	respond_to do |format|
		    format.html  # show.html.erb
		    format.json  { render :json => @posts }
	    end
	end

	def index
	  @posts = Post.all
	 
	  respond_to do |format|
	    format.html  # index.html.erb
	    format.json  { render :json => @posts }
	  end
	end

	def edit
		@post = Post.find(params[:id])
	end
	
	# def update
	# 	@post = Post.find(params[:id])

	# 	#if @post.update(params[:post].permit(:title, :text))
	# 	if @post.update(params[:post])
	# 		redirect_to @post
	# 	else
	# 		render 'edit'
	# 	end
	# end
	def update
	  @post = Post.find(params[:id])
	 
	  respond_to do |format|
	    if @post.update_attributes(params[:post])
	      format.html  { redirect_to(@post, :notice => 'Post was successfully updated.') }
	      format.json  { head :no_content }
	    else
	      format.html  { render :action => "edit" }
	      format.json  { render :json => @post.errors,
	                    :status => :unprocessable_entity }
	    end
	  end
	end

	def destroy
		@post = Post.find(params[:id])
		@post.destroy

		respond_to do |format| 
			format.html {redirect_to posts_url}
			format.json { head :no_content}
		end
	end

	private
	  def post_params
	    params.require(:post).permit(:title, :text)
	  end

end

app/controllers/signin_controller.rb
class SigninController < ApplicationController
	def signin
		#render text: params[:post].inspect
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	@user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  def create
  	@user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to expenses_url, notice: "User has successfully created.", alert: "Yeh success"}
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def index
    @users = User.all

    respond_to do |format|
      format.html #index.html.erb
      format.json { render json: @users }
    end
  end

  def show
    @user = User.find(params[:id])


    respond_to do |format|
      format.html  # show.html.erb
      format.json  { render :json => @users }
    end
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/signin_helper.rb
module SigninHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/expenses/_form.html.erb
<%= form_for(@expense) do |f| %>
  <% if @expense.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@expense.errors.count, "error") %> prohibited this expense from being saved:</h2>

      <ul>
      <% @expense.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :categories %><br />
    <%= f.text_field :categories %>
  </div>
  <div class="field">
    <%= f.label :amount %><br />
    <%= f.text_field :amount %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/expenses/edit.html.erb
<h1>Editing expense</h1>

<%= render 'form' %>

<%= link_to 'Show', @expense %> |
<%= link_to 'Back', expenses_path %>

app/views/expenses/index.html.erb
<h1>Listing expenses</h1>

<table>
  <tr>
    <th>Categories</th>
    <th>Amount</th>
    <th>Description</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @expenses.each do |expense| %>
  <tr>
    <td><%= expense.categories %></td>
    <td><%= expense.amount %></td>
    <td><%= expense.description %></td>
    <td><%= expense.email %></td>
    <td><%= link_to 'Show', expense %></td>
    <td><%= link_to 'Edit', edit_expense_path(expense) %></td>
    <td><%= link_to 'Destroy', expense, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Expense', new_expense_path %>

app/views/expenses/new.html.erb
<h1>New expense</h1>

<%= render 'form' %>

<%= link_to 'Back', expenses_path %>

app/views/expenses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Categories:</b>
  <%= @expense.categories %>
</p>

<p>
  <b>Amount:</b>
  <%= @expense.amount %>
</p>

<p>
  <b>Description:</b>
  <%= @expense.description %>
</p>

<p>
  <b>Email:</b>
  <%= @expense.email %>
</p>


<%= link_to 'Edit', edit_expense_path(@expense) %> |
<%= link_to 'Back', expenses_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Planner</title>    
      <%= stylesheet_link_tag    "application", :media => "all" %>
	  <%= javascript_include_tag "application" %>
	  <%= csrf_meta_tags %>
	<!-- <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}"> -->
  </head>
  <body>
	<header>
	  <div class="container">
	    <h1 class="logo">Bplanner</h1>
	    <nav>
	      <ul class="menu">

        	<li><%= link_to "Home", root_path %></li>
		    <li><%= link_to "Budget", expenses_path %></li>
		    <li>
            <%= link_to "Expense", new_expense_path %>
		    </li>
		    <!-- {% if 'email' in session %}
		    <li><a href="{{ url_for('profile') }}">Profile</a></li>
		    <li><a href="{{ url_for('signout') }}">Sign Out</a></li>
		    {% else %}
		    <li><a href="{{ url_for('signup') }}">Sign Up</a></li>
		    <li><a href="{{ url_for('signin') }}">Sign In</a></li>
		    {% endif %} -->
	      </ul>

	    </nav>
	  </div>
	</header>
   <div class="hd-line"></div>

    <div class="container">
		<% if notice %>
		  <p class="alert alert-notice"><%= notice %></p>
		<% end %>
		<% if alert %>
		  <p class="alert alert-error"><%= alert %></p>
		<% end %>
		<p class="navbar-text pull-right">
		<%= yield %>
    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
  <div id="errorExplanation">
    <h2><%= pluralize(@post.errors.count, "error") %> prohibited
        this post from being saved:</h2>
    <ul>
    <% @post.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :text %><br />
    <%= f.text_area :text %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>
<%= render 'form' %> 
<%= link_to 'Back', posts_path %>
<%= link_to 'Show', @post %>

app/views/posts/index.html.erb
<h1>Information!</h1>
<%= link_to "List", controller: "posts" %>

<%= link_to 'Add Post', new_post_path %>
<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
  </tr>
 
  <% @posts.each do |post| %>
    <tr>
      <td><%= post.title %></td>
      <td><%= post.text %></td>
      <td><%= link_to 'Show', post %></td>
      <td><%= link_to 'Edit', edit_post_path(post) %></td>
      <td><%= link_to 'Destroy', post, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

app/views/posts/new.html.erb
<h1>New Post</h1>
<%= render 'form' %>
<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @post.text %>
</p>

<%= link_to 'Back', posts_path %> | <%= link_to 'Edit', edit_post_path(@post) %>

<p id="notice"><%= notice %></p>

app/views/signin/signin.html.erb
<h1>Sign In</h1>

<% form_for :signin do |f| %>
<p><% = f.text_field :username %> </p>
<p><% = f.text_field :password %> </p>
<p><%= f.submit %></p>
<% end %> 

app/views/users/index.html.erb
<h1>List Of Users</h1>

<table>
  <tr>
    <th>Categories</th>
    <th>Amount</th>
    <th>Description</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.firstname %></td>
    <td><%= user.lastname %></td>
    <td><%= user.email %></td>
    <td><%= user.password %></td>
    <td><%= link_to 'Show', :controller => 'users', :action => 'new' %></td>
  </tr>
<% end %>
</table>

<br />
<p id="notice"> <% if notice %> <%= notice %><%= alert %><% end %> 
</p>

app/views/users/new.html.erb
<% @page_title = "UserAuth | Signup" %>
<div class="Sign_Form">
  <h1>Sign Up</h1>
  <%= form_for(:user, :url => {:controller => 'users', :action => 'create'}) do |f| %>
  <!--< %= form_for @user, :url => {:controller => :users, :action => 'create'} do |f| %>
  < %= form_for @user, :url => url_for(:controller => 'users', :action => 'create') do |f| %>-->
  
    <p> Firstname: <br/><%= f.text_field :firstname %> </p>
    <p> Lastname: <br/><%= f.text_field :lastname %> </p>
    <p> Email: <br/> <%= f.text_field :email%> </p>
    <p> Password:<br/> <%= f.password_field :password%></p>
    <p> Password Confirmation:<br/> <%= f.password_field :password_confirmation%> </p>
    <%= f.submit :Signup %>
  <% end %>
  <% if @user.errors.any? %>
    <ul class="Signup_Errors">
    <% for message_error in @user.errors.full_messages %>
      <li>* <%= message_error %></li>
    <% end %>
    </ul>
  <% end %>
</div>

app/views/users/show.html.erb
<p>
  <strong>Firstname:</strong>
  <%= @user.firstname %>
</p>
<p>
  <strong>Lastname:</strong>
  <%= @user.lastname %>
</p>
<p id="notice"><%= notice %></p>

app/views/welcome/index.html.erb
<!--<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>-->
  <div class="jumbo">
  	<% if appuser_signed_in? %>  
    <h2>Profile<h2>
	<h3>This is <%= current_appuser.email %> 's profile page<h3>
	<% else %>
		<h3>Greetings!</h3>
	<% end %>
  </div>


<% if appuser_signed_in? %>
  <!-- Logged in as <strong><%= current_appuser.email %></strong>.   <%= session.inspect %> -->
  <%= link_to 'Edit profile', edit_appuser_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_appuser_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Sign up", new_appuser_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Sign In", new_appuser_session_path, :class => 'navbar-link'  %>
<% end %>